name: 01 - Building Blocks

on: [push, workflow_dispatch]

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    name: Say hello
    steps:
      - run: echo "Hello, World!"

  echo-goodbye:
    runs-on: ubuntu-latest
    name: Say goodbye
    steps:
      - run: echo "Goodbye!"